<?php

$FP_CURRENCY = '&euro;';
$FP_CURRENCY_NAME = "EUR";
$FP_DECIMAL = ",";
$FP_THOUSANDS = ".";

// name of currency is if used after, e.g. USD
$FP_CURRENCY_AFTER = "EUR";

// PAYPAL FRAMESHOP SETTINGS
$FP_PAYPAL_CURRENCY_CODE = "EUR";

// Framing using HTML and graphics
$SYSTEM_FRAMESTYLES  = array (
	0=>" No Frame",
	1=>"Black Metal",
	2=>"Wood", 
	3=>"Gold Leaf", 
	4=>"Baroque Gold", 
	5=>"Diasec"
);

// These correspond to $SYSTEM_FRAMESTYLES. These are allowed widths.
$FRAMESTYLESWIDTHS 	= array (0=>"0", 1=>"7", 2=>"10", 3=>"15", 4=>"20", 5=>"1");

?>