<?php

// Make navbar solid
$FP_SOLIDIFY = true;

// Resize screen to fit bkgd picture in certain themes
$FP_RESIZE_TO_BKGD_IMAGE  = true;

// Opacity of watermark on a picture (between 0=opaque and 127=transparent)
$FP_WATERMARK_OPACITY = 70;

// Size of font used for watermarking, for built-in PHP fonts. 1 is small, 5 is large
$FP_WATERMARK_FONT_SIZE = 48.0;
// Font directory for TrueType fonts
$FP_WATERMARK_FONT_DIR = "fonts";
// Font must be a .ttf font (TrueType) and must be in "fonts" folder
$FP_WATERMARK_FONT_NAME = "Vera.ttf";


//$slide_size		= array (1500, 800);	// works well for 1900x1200 and larger
$slide_size		= array (1500, 1000);	// works well for 1900x1200 and larger

?>