<?php

/*
	Shipping Configuration
	
*/

$UPS_PRODUCT_CODES = array (
	"1DM" => 'UPS Next Day Air Early AM',
	"1DA" => 'UPS Next Day Air',
	"1DP" => 'UPS Next Day Air Saver',
	"2DM" => 'UPS 2nd Day Air Early AM',
	"2DA" => 'UPS 2nd Day Air',
	"3DS" => 'UPS 3 Day Select',
	"GND" => 'UPS Ground',
	"STD" => 'UPS Canada',
	"XPR" => 'UPS Worldwide Express',
	"XDM" => 'UPS Worldwide Express Plus',
	"XPD" => 'UPS Worldwide Expedited',
	);


?>